[package]
name = "scabbard"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Philip Linden", "Colin Jacobs"]
license = "MIT"
description = "A Typst template for creating Draw Steel RPG content including stat blocks, spell cards, and adventure modules. Forced from dragonling by Colin Jacobs."
repository = "https://github.com/philiplinden/typst-draw-steel"
keywords = ["roleplaying", "dnd", "dungeons-dragons", "rpg", "template", "gaming", "draw-steel", "ttrpg", "mcdm", "draw", "steel"]
categories = ["layout", "report"]
compiler = "0.13.0"
exclude = ["example"]
